### ISSUE TITLE
Labeling the fire

### ISSUE THREAD

**Issue by AlaaSerhal** [bubblebeam/Inferno-Realtime-Fire-detection-using-CNNs#1]
Can this project be edited so that we can have a bounding box around the fire? I want to detect exactly the fire in the frame captured. Can you please provide with the steps to take or the functions to use. I checked on the internet but it seems that there are files that missing. Looking forward to your answer, thank you in advance.

**Comment by bala-shankar** [comment]
Iam a final year student iam gonna work on this topic so can u please guide me :)

**Comment by bubblebeam** [comment]
@AlaaSerhal  sorry for the late reply. But threadcv.py file has the code for the bounding box around the fire.
